 theme: jekyll-theme-minimal
 title: Aljawharah Alzahrani Page
 description: Hi, I'm Aljawharah Alzahrani, a PhD student in informatics at Pennsylvania State University’s College of Information Sciences and Technology. I am fortunate to be advised by Dr.Tanusree Sharma. My research focuses on privacy, cross-cultural perspectives, and human–computer interaction
